var block,bookNo,lastWord,voiceList,utterance,progress="bilingual",sensitivity="base",hideText=!1,test=!0,firstMistake,entry=document.getElementById("entry"),book=[document.getElementById("book0"),document.getElementById("book1")];book[0].regex=RegExp();book[1].regex=RegExp();speechSynthesis.cancel();
window.onunload=function(){var a=document.getElementsByTagName("select");localStorage.voice0=a[0].selectedIndex;localStorage.voice1=a[1].selectedIndex;localStorage.mode=test;localStorage.highlight=book[0].classList.contains("highlight");localStorage.sensitivity=sensitivity;localStorage.hideText=hideText;localStorage.progress=progress};
for(var i=0;2>i;i++)book[i].onmouseup=mouseUpFunc(i),book[i].ondragover=function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"},book[i].ondragenter=book[i].ondragover,book[i].ondrop=bookDropFunc(i),clearBook(i),book[i].ondblclick=dblClickFunc(i);
function mouseUpFunc(a){return function(){var b=getSelection().anchorNode;void 0!=b&&void 0!=b.data&&void 0!=book[a].text&&(book[a].regex.lastIndex=getSelection().anchorOffset+book[a].text.indexOf(b.data),speaking()&&(cancelSpeech(),"Resume"!=document.getElementById("btnPause").textContent&&readText()));test&&entry.focus()}}function dblClickFunc(a){return function(){var b=document.getElementById("file"+a);b&&b.click()}}
function bookDropFunc(a){return function(b){b.stopPropagation();b.preventDefault();fetchFile(b.dataTransfer.files[0],a)}}
speechSynthesis.onvoiceschanged=function(){var a=document.getElementsByTagName("select");if(0==a[0].length){voiceList=this.getVoices();for(var b=0;b<voiceList.length;b++){var c=voiceList[b].name.replace("Google ","");a[0].add(new Option(c,b));a[1].add(new Option(c,b))}a[0].onchange=function(){book[0].voice=voiceList[this.selectedIndex]};a[1].onchange=function(){book[1].voice=voiceList[this.selectedIndex]};getDemoTexts();if(null!==localStorage.getItem("mode"))for(a[0].selectedIndex=localStorage.voice0,
a[1].selectedIndex=localStorage.voice1,changeControls("true"==localStorage.mode),test||(document.getElementsByName("mode")[1].checked=!0),"false"==localStorage.highlight&&(book[0].classList.remove("highlight"),book[1].classList.remove("highlight"),document.getElementById("chkHighlight").checked=!1),sensitivity=localStorage.sensitivity,"base"!=sensitivity&&(document.getElementById("chkAccent").checked=!0),"true"==localStorage.hideText&&(hideText=document.getElementById("chkHideText").checked=!0),progress=
localStorage.progress,c=document.getElementsByName("progress"),b=0;b<c.length;b++)c[b].checked=c[b].value==progress;else for(b=0;b<a[1].length;b++)if("fr"==a[1].options[b].text.substr(0,2).toLowerCase()){a[1].selectedIndex=b;break}a[0].onchange();a[1].onchange();changeDual()}};document.getElementsByName("mode")[0].onchange=function(){changeControls(!0);entry.focus()};document.getElementsByName("mode")[1].onchange=function(){changeControls(!1)};
function changeDual(){var a="bilingual"==progress?"dual":"single";document.getElementById("container0").className=a;document.getElementById("container1").className=a;test&&entry.focus()}entry.onkeydown=function(){this.placeholder="";this.onkeydown=null};
entry.oninput=function(){var a=tidyString(this.value),b=a.length,c=tidyString(block);0==a.localeCompare(c.substr(0,b),book[bookNo].voice.lang,{sensitivity:sensitivity})?(this.maxLength=999,this.style.color="black",b==c.length&&(hideText&&(book[bookNo].textContent=book[bookNo].text.substr(0,book[bookNo].regex.lastIndex)),"bilingual"==progress&&(bookNo=1-bookNo),readText())):"red"!=this.style.color&&(this.style.color="red",this.maxLength=b,"word"!=progress&&(a=c.indexOf(" ",b-1),0>a&&(a=c.len),b=c.lastIndexOf(" ",
b-2),c=c.substring(b+1,a)),c!=lastWord?(lastWord=c,firstMistake=!0):firstMistake?(firstMistake=!1,sayWord(c)):(spellWord(c,0),firstMistake=!0))};function changeControls(a){test=a;document.getElementById("typeDiv").style.display=a?"block":"none";test&&speaking()&&(entry.disabled=!1,entry.focus());a=a?"inline":"none";entry.style.display=a;document.getElementById("lblAccent").style.display=a;document.getElementById("lblHideText").style.display=a}
function speaking(){return void 0!=utterance&&null!=utterance.onend}document.getElementById("btnStart").onclick=function(){0<book[0].getElementsByTagName("input").length||"bilingual"==progress&&0<book[1].getElementsByTagName("input").length||("Resume"==document.getElementById("btnPause").textContent||speaking()?resetToStart():reset(),entry.focus(),readText())};function reset(){entry.disabled=!1;document.getElementById("btnPause").textContent="Pause";setRegex()}
function resetToStart(){cancelSpeech();reset();for(var a=0;2>a;a++)book[a].regex.lastIndex=0,bookNo=book[a].scrollTop=0}document.getElementById("btnPause").onclick=function(){"Resume"==this.textContent?(speaking()?speechSynthesis.resume():readText(),this.textContent="Pause"):speaking()&&(speechSynthesis.pause(),this.textContent="Resume",entry.disabled=!0);test&&entry.focus()};
document.getElementById("btnRepeat").onclick=function(){document.getElementById("btnPause").textContent="Pause";cancelSpeech();test&&entry.focus();"bilingual"==progress||"sentence"==progress?speakBlock(!1,phraseRegExp()):speakBlock(!1)};function cancelSpeech(){utterance&&(utterance.onend=null,speechSynthesis.cancel())}document.getElementsByName("progress")[0].onchange=function(){progress=this.value;changeDual();setRegex()};document.getElementsByName("progress")[1].onchange=document.getElementsByName("progress")[0].onchange;
document.getElementsByName("progress")[2].onchange=document.getElementsByName("progress")[0].onchange;document.getElementsByName("progress")[3].onchange=function(){progress=this.value;changeDual();resetToStart()};document.getElementById("chkAccent").onchange=function(){sensitivity=this.checked?"accent":"base"};document.getElementById("chkHideText").onchange=function(){hideText=this.checked;for(var a=0;2>a;a++)0==book[a].getElementsByTagName("input").length&&(book[a].textContent=hideText?"":book[a].text)};
document.getElementById("chkHighlight").onchange=function(){book[0].classList.toggle("highlight");book[1].classList.toggle("highlight")};function fetchFile(a,b){var c=new FileReader;c.onload=function(){a instanceof File&&(book[b].file=a);processBook(a.name,this.result,b)};c.readAsBinaryString(a)}
function processBook(a,b,c){book[c].innerHTML="";b=b.replace(/'/g,"&#8217;").replace(/"(?! )/g,"&#8220;").replace(/"/g,"&#8221;").replace(/(Mr*s*)\./g,"$1");var f=b.indexOf("<p>");if(0>f)book[c].insertAdjacentHTML("afterbegin",b),book[c].text=b;else{var d=b.lastIndexOf("</p>");0>d&&(d=b.len-1);book[c].insertAdjacentHTML("afterbegin",b.substring(f,d));book[c].text=book[c].textContent}hideText&&(book[c].textContent="");b=document.createElement("button");b.insertAdjacentHTML("afterbegin","Clear");b.title=
"Remove the current book, ready to import a new one";var e=document.getElementById("title"+c);e.innerHTML=a;e.appendChild(b);b.onclick=function(){e.innerHTML="";resetToStart();clearBook(c)};book[c].style.textAlign="justify";resetToStart()}function getDemoTexts(){downloadFile("http://www.silvawood.co.uk/dictutorial/Swann's Way - Overture (Proust).htm",0);downloadFile("http://www.silvawood.co.uk/dictutorial/Du c%F4t%E9 de chez Swann - Combray (Proust).htm",1)}
function downloadFile(a,b){var c=new XMLHttpRequest;c.open("GET",a);c.responseType="blob";c.onload=function(){this.response.name=0==b?"Swann's Way - Overture (Proust)":"Du c&ocirc;t&eacute; de chez Swann - Combray";fetchFile(this.response,b)};c.send()}
function clearBook(a){book[a].innerHTML='<cite>Drag/drop a text or html file here<br>or double click to <input id="file'+a+'" type="file" accept=".txt,.htm,.html"></cite>';document.getElementById("file"+a).onchange=function(){this.files[0]&&fetchFile(this.files[0],a)}}
function setRegex(){var a=book[0].regex.lastIndex;if("phrase"==progress)book[0].regex=phraseRegExp();else if("word"==progress)book[0].regex=RegExp("\\S+","g");else{book[0].regex=/[^.]+[.!\?]+["'\u201C\u201D\u00AB\u00BB]*(?=\s+)/g;var b=book[1].regex.lastIndex;book[1].regex=/[^.]+[.!\?]+["'\u201C\u201D\u00AB\u00BB]*(?=\s+)/g;book[1].regex.lastIndex=b}book[0].regex.lastIndex=a}
function phraseRegExp(){return RegExp("[^,:;\\(\\)\\.\\?\\[\\]\\{\\}'\\u201C\\u201D\\u00BB\"]+[,:;\\(\\)\\.\\?\\[\\]\\{\\}'\\u201C\\u201D\\u00BB\"]+","g")}
function readText(){if(!speechSynthesis.paused){var a=book[bookNo].regex.exec(book[bookNo].text);if(block=a[0]){var b=book[bookNo];hideText||(b.innerHTML=book[bookNo].text.substr(0,a.index)+"<span>"+block+"</span>"+book[bookNo].text.substr(book[bookNo].regex.lastIndex),b.childNodes[1].offsetTop+b.childNodes[1].offsetHeight-b.offsetTop-b.scrollTop>b.offsetHeight&&(b.scrollTop=b.childNodes[1].offsetTop-b.offsetTop));test&&entry.focus();"bilingual"==progress||"sentence"==progress?speakBlock(test,phraseRegExp()):
speakBlock(test)}else book.style.color="blue",test&&(entry.onchange=null)}}
function speakBlock(a,b){if(b){var c=b.exec(block);utterance=new SpeechSynthesisUtterance(c[0]);utterance.onend=function(){b.lastIndex==block.length?test?entry.focus():("bilingual"==progress&&(bookNo=1-bookNo),readText()):speakBlock(!1,b)}}else utterance=new SpeechSynthesisUtterance(block),utterance.onend=function(){test||readText()};a&&(utterance.onstart=function(){entry.value=""});utterance.voice=book[bookNo].voice;speechSynthesis.speak(utterance)}
function tidyString(a){return a.replace(RegExp("[\\u201A-\\u206F\\u2E00-\\u2E7F\\u00BB\\u00AB\\u2018\\u2019'!#%&,-/:;<=>@_`~\\$\\(\\)\\*\\+\\.\\?\\[\\]\\^\\{\\|\\}\"]","g"),"").trim().replace(/\s+/g," ")}function sayWord(a){utterance=new SpeechSynthesisUtterance(a);utterance.voice=book[bookNo].voice;speechSynthesis.speak(utterance)}
function spellWord(a){for(var b=0;b<a.length;b++)utterance=new SpeechSynthesisUtterance(a.charAt(b)),utterance.voice=book[bookNo].voice,speechSynthesis.speak(utterance)};